# Generated by Django 3.0.4 on 2020-04-17 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='active_orders_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by_id', models.IntegerField()),
                ('order_by_name', models.CharField(max_length=50)),
                ('food_id', models.IntegerField()),
                ('address', models.TextField(max_length=100)),
                ('resturent', models.CharField(max_length=20, null=True)),
                ('food_name', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='item_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resto_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('tag', models.CharField(max_length=40)),
                ('item_type', models.CharField(choices=[('veg', 'veg'), ('non-veg', 'non-veg')], default=1, max_length=10)),
                ('image', models.ImageField(upload_to='uploads/itemsimg/')),
                ('price', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
